server:
  port: 8080
spring:
  application:
    name: 100kps
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        min-idle: 4
        max-idle: 8
    timeout: 30000
mybatis:
  type-aliases-package: com.sly.demo100.model
  mapper-locations:
  - classpath*:/mapper/*.xml
